spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/oasis
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

api-spec:
  kakao:
    blog:
      host: https://dapi.kakao.com
      uri: /v2/search/blog
    rest:
      apikey: ${kakao.rest.apikey}




